### ISSUE TITLE
Daten löschen (HTTP DELETE)

### ISSUE THREAD

**Issue by surech** [SchweizerischeBundesbahnen/roterOktober-server#15]
Beim Löschen soll der Datensatz nicht wirklich gelöscht werden, sondern nur ein Flag sowie das Löschdatum gesetzt werden. Beim Auslesen (GET) muss dann sichergestellt werden, dass die Einträge mit gesetzten "Gelöscht"-Flag nicht zurückgegeben werden.

**Comment by surech** [comment]
Das Löschen der einzelnen Entitäten ist umgesetzt. Was noch fehlt ist das kaskadierte Löschen: Sprich wenn man den Mitarbeiter löscht sollten auch seine Einsätze und Pensen verschwinden.

**Comment by mwalter** [comment]
Dein zweiter Kommentar steht im Widerspruch zum ersten. Sollen die Datensätze nun gelöscht werden oder nur als gelöscht markiert werden?

**Comment by surech** [comment]
Es stimmt beides 😉 Das Löschen ist wie im ersten Kommentar beschrieben umgesetzt. Der Datensatz bleibt erhalten und es wird nur ein Flag gesetzt. 
Mit dem zweiten Kommentar will ich sagen, dass das Flag kaskadiert gesetzt werden muss. Den ein Einsatz ohne Mitarbeiter macht wenig Sinn.
