### ISSUE TITLE
Build Ergebnisse sichtbar machen

### ISSUE THREAD

**Issue by mwalter** [SchweizerischeBundesbahnen/roterOktober-server#29]
Als Entwickler möchte ich sehen können, ob der Build erfolgreich war. Den Status des Builds kann man idealerweise direkt der README.md entnehmen. Builds könnten via https://drone.io getriggert werden.

**Comment by surech** [comment]
Inzwischen gibt es einen Nightly-Build auf dem SBB-Jenkins-Server inkl. Deployment in die Cloud. Gerne kann ich dir die URLs zuschicken, möchte sie aber lieber nicht hier publizieren. 
Wir können aber drone.io gerne mal ausprobieren.

**Comment by surech** [comment]
Wow, drone.io ist wirklich cool! So schnell habe ich noch nie einen CI-Build eingerichtet:
https://drone.io/github.com/SchweizerischeBundesbahnen/roterOktober-server/2

**Comment by mwalter** [comment]
Gell, coole Sache! 👍 Leider hab ich keinen Zugriff auf die Drone.io-Settings. Du kannst von dort den Link zum Status Badge kopieren und in die README.md einfügen.

**Comment by surech** [comment]
Jetzt hast du die Rechte.
